import { Threat, ActivityDataPoint, AssetImpact } from '@/types/threat';

export const mockThreats: Threat[] = [
  {
    id: 't001',
    name: 'BadBox 2.0',
    asset: 'Okta',
    severity: 'High',
    status: 'Active',
    first_seen: '2025-10-20T14:30:00Z',
    last_updated: '2025-10-27T09:15:00Z',
    score: 78,
    description: 'Critical vulnerability in Okta authentication service allowing potential account takeover through session hijacking. Attackers can exploit weak session management to gain unauthorized access.',
    source: 'CISA',
    cves: ['CVE-2025-8401', 'CVE-2025-8402'],
    kill_chain_phase: 'Initial Access',
    confidence: 'High',
    affected_versions: ['2024.8.x', '2024.9.x'],
    iocs: [
      { type: 'IP', value: '192.168.1.100', first_seen: '2025-10-20T14:30:00Z' },
      { type: 'Domain', value: 'malicious-okta.com', first_seen: '2025-10-21T08:00:00Z' },
    ],
    geo: { lat: 37.7749, lon: -122.4194 },
    recommended_actions: [
      'Update Okta to version 2024.10.1 or later',
      'Review authentication logs for suspicious activity',
      'Enable multi-factor authentication for all users',
      'Rotate API keys and session tokens',
    ],
  },
  {
    id: 't002',
    name: 'GLOBAL Ransomware',
    asset: 'Windows Servers',
    severity: 'Critical',
    status: 'New',
    first_seen: '2025-10-26T18:45:00Z',
    last_updated: '2025-10-27T10:00:00Z',
    score: 95,
    description: 'New ransomware strain targeting Windows Server infrastructure with advanced encryption mechanisms. Spreads through SMB vulnerabilities and executes fileless attacks.',
    source: 'Vendor',
    cves: ['CVE-2025-9801'],
    kill_chain_phase: 'Execution',
    confidence: 'Critical',
    affected_versions: ['Server 2019', 'Server 2022'],
    iocs: [
      { type: 'Hash', value: 'a1b2c3d4e5f6...', first_seen: '2025-10-26T18:45:00Z' },
      { type: 'C2', value: 'c2.ransomware-global.xyz', first_seen: '2025-10-26T19:00:00Z' },
      { type: 'File', value: 'encrypt.exe', first_seen: '2025-10-26T19:15:00Z' },
    ],
    geo: { lat: 51.5074, lon: -0.1278 },
    recommended_actions: [
      'Immediately isolate affected servers',
      'Apply Microsoft security patches KB5123456',
      'Disable SMBv1 protocol',
      'Restore from verified backups',
      'Engage incident response team',
    ],
  },
  {
    id: 't003',
    name: 'Chrome CVE-2025-10585',
    asset: 'Chrome Browser',
    severity: 'High',
    status: 'Active',
    first_seen: '2025-10-15T08:00:00Z',
    last_updated: '2025-10-26T16:30:00Z',
    score: 82,
    description: 'Type confusion vulnerability in V8 JavaScript engine allowing remote code execution. Affects Chrome versions prior to 130.0.6723.92.',
    source: 'Vendor',
    cves: ['CVE-2025-10585'],
    kill_chain_phase: 'Exploitation',
    confidence: 'High',
    affected_versions: ['< 130.0.6723.92'],
    iocs: [
      { type: 'URL', value: 'hxxps://exploit-chrome[.]net/rce', first_seen: '2025-10-15T08:00:00Z' },
    ],
    geo: { lat: 40.7128, lon: -74.0060 },
    recommended_actions: [
      'Update Chrome to version 130.0.6723.92 or later',
      'Deploy browser isolation for critical users',
      'Monitor for suspicious JavaScript execution',
    ],
  },
  {
    id: 't004',
    name: 'GRUB2 Bootloader Exploit',
    asset: 'Linux Servers',
    severity: 'Medium',
    status: 'Active',
    first_seen: '2025-10-10T12:00:00Z',
    last_updated: '2025-10-25T14:20:00Z',
    score: 65,
    description: 'Buffer overflow in GRUB2 bootloader allowing local privilege escalation. Requires physical access or already compromised system.',
    source: 'CERT-IN',
    cves: ['CVE-2025-7723'],
    kill_chain_phase: 'Privilege Escalation',
    confidence: 'Medium',
    affected_versions: ['GRUB 2.04', 'GRUB 2.06'],
    iocs: [],
    recommended_actions: [
      'Update GRUB2 to patched version',
      'Enable Secure Boot',
      'Review physical access controls',
    ],
  },
  {
    id: 't005',
    name: 'PhishKit Orion',
    asset: 'Email Gateway',
    severity: 'Low',
    status: 'Mitigated',
    first_seen: '2025-10-05T09:30:00Z',
    last_updated: '2025-10-24T11:00:00Z',
    score: 45,
    description: 'Phishing campaign using Orion phishing kit targeting Office 365 credentials. Low sophistication, easily detectable.',
    source: 'Internal',
    kill_chain_phase: 'Initial Access',
    confidence: 'Low',
    iocs: [
      { type: 'Email', value: 'support@0ffice365-login[.]com', first_seen: '2025-10-05T09:30:00Z' },
      { type: 'Domain', value: '0ffice365-login[.]com', first_seen: '2025-10-05T09:45:00Z' },
    ],
    recommended_actions: [
      'Block sender domain',
      'User awareness training completed',
    ],
  },
  {
    id: 't006',
    name: 'Apache Struts RCE',
    asset: 'Web Applications',
    severity: 'Critical',
    status: 'Active',
    first_seen: '2025-10-22T10:15:00Z',
    last_updated: '2025-10-27T08:45:00Z',
    score: 92,
    description: 'Remote code execution vulnerability in Apache Struts framework. Actively exploited in the wild.',
    source: 'CISA',
    cves: ['CVE-2025-9900'],
    kill_chain_phase: 'Exploitation',
    confidence: 'Critical',
    affected_versions: ['2.5.30', '2.5.31'],
    iocs: [
      { type: 'IP', value: '203.0.113.42', first_seen: '2025-10-22T10:15:00Z' },
      { type: 'User-Agent', value: 'Mozilla/5.0 (exploit)', first_seen: '2025-10-22T11:00:00Z' },
    ],
    geo: { lat: 35.6762, lon: 139.6503 },
    recommended_actions: [
      'Patch to Apache Struts 2.5.32 immediately',
      'Review web application logs',
      'Implement WAF rules',
    ],
  },
  {
    id: 't007',
    name: 'AWS S3 Misconfig',
    asset: 'AWS S3',
    severity: 'Medium',
    status: 'New',
    first_seen: '2025-10-26T15:00:00Z',
    last_updated: '2025-10-27T07:30:00Z',
    score: 58,
    description: 'Publicly accessible S3 bucket containing sensitive customer data. Misconfiguration detected by automated scan.',
    source: 'Internal',
    kill_chain_phase: 'Initial Access',
    confidence: 'High',
    recommended_actions: [
      'Immediately set bucket to private',
      'Review bucket policies',
      'Audit data exposure',
      'Enable S3 Block Public Access',
    ],
  },
  {
    id: 't008',
    name: 'Log4Shell Revival',
    asset: 'Java Applications',
    severity: 'High',
    status: 'Active',
    first_seen: '2025-10-18T13:20:00Z',
    last_updated: '2025-10-27T09:00:00Z',
    score: 85,
    description: 'New variant of Log4Shell vulnerability targeting unpatched Java applications. Uses novel JNDI lookup patterns.',
    source: 'Vendor',
    cves: ['CVE-2025-8888'],
    kill_chain_phase: 'Exploitation',
    confidence: 'High',
    affected_versions: ['Log4j 2.0-2.17.0'],
    iocs: [
      { type: 'Pattern', value: '${jndi:ldap://evil[.]com/x}', first_seen: '2025-10-18T13:20:00Z' },
    ],
    recommended_actions: [
      'Update Log4j to 2.18.0+',
      'Deploy JNDI lookup restrictions',
      'Scan for vulnerable applications',
    ],
  },
  {
    id: 't009',
    name: 'Kubernetes API Exposure',
    asset: 'Kubernetes',
    severity: 'High',
    status: 'Active',
    first_seen: '2025-10-20T11:00:00Z',
    last_updated: '2025-10-26T16:00:00Z',
    score: 80,
    description: 'Kubernetes API server exposed to internet without authentication. Immediate risk of cluster compromise.',
    source: 'Internal',
    confidence: 'Critical',
    recommended_actions: [
      'Restrict API server access to internal networks',
      'Enable RBAC',
      'Rotate service account tokens',
      'Audit cluster configurations',
    ],
  },
  {
    id: 't010',
    name: 'Supply Chain: npm Package',
    asset: 'NPM Registry',
    severity: 'Medium',
    status: 'New',
    first_seen: '2025-10-25T14:00:00Z',
    last_updated: '2025-10-27T08:00:00Z',
    score: 70,
    description: 'Malicious npm package "colors-v2" contains cryptocurrency miner. Downloaded 50K+ times before detection.',
    source: 'Vendor',
    kill_chain_phase: 'Execution',
    confidence: 'High',
    iocs: [
      { type: 'Package', value: 'colors-v2@1.4.0', first_seen: '2025-10-25T14:00:00Z' },
    ],
    recommended_actions: [
      'Remove package from projects',
      'Scan codebase for similar threats',
      'Review npm audit logs',
      'Implement software composition analysis',
    ],
  },
  {
    id: 't011',
    name: 'PostgreSQL Auth Bypass',
    asset: 'PostgreSQL',
    severity: 'Critical',
    status: 'Active',
    first_seen: '2025-10-23T09:00:00Z',
    last_updated: '2025-10-27T10:30:00Z',
    score: 90,
    description: 'Authentication bypass in PostgreSQL versions 14.x-16.x allowing unauthenticated remote access.',
    source: 'CISA',
    cves: ['CVE-2025-9555'],
    kill_chain_phase: 'Initial Access',
    confidence: 'Critical',
    affected_versions: ['14.0-14.9', '15.0-15.4', '16.0-16.1'],
    recommended_actions: [
      'Patch PostgreSQL immediately',
      'Review access logs',
      'Reset all database passwords',
      'Implement network segmentation',
    ],
  },
  {
    id: 't012',
    name: 'Redis Unauth Access',
    asset: 'Redis',
    severity: 'Low',
    status: 'Mitigated',
    first_seen: '2025-10-12T16:00:00Z',
    last_updated: '2025-10-23T12:00:00Z',
    score: 40,
    description: 'Redis instance exposed without authentication. Fixed by enabling authentication and firewall rules.',
    source: 'Internal',
    recommended_actions: [
      'Verification scan completed',
    ],
  },
];

export const mockActivityData: ActivityDataPoint[] = [
  { date: '2025-10-21', Critical: 1, High: 3, Medium: 2, Low: 1 },
  { date: '2025-10-22', Critical: 2, High: 4, Medium: 3, Low: 2 },
  { date: '2025-10-23', Critical: 1, High: 5, Medium: 4, Low: 1 },
  { date: '2025-10-24', Critical: 0, High: 3, Medium: 3, Low: 2 },
  { date: '2025-10-25', Critical: 1, High: 4, Medium: 5, Low: 2 },
  { date: '2025-10-26', Critical: 2, High: 5, Medium: 4, Low: 1 },
  { date: '2025-10-27', Critical: 2, High: 6, Medium: 3, Low: 2 },
];

export const mockAssetImpacts: AssetImpact[] = [
  { asset: 'Windows Servers', count: 2 },
  { asset: 'Web Applications', count: 1 },
  { asset: 'AWS S3', count: 1 },
  { asset: 'Okta', count: 1 },
  { asset: 'Chrome Browser', count: 1 },
  { asset: 'Java Applications', count: 1 },
  { asset: 'Kubernetes', count: 1 },
  { asset: 'PostgreSQL', count: 1 },
  { asset: 'NPM Registry', count: 1 },
  { asset: 'Linux Servers', count: 1 },
];
